version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: demo1234
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: demo1234
    ports:
      - "5050:80"

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # MinIO API
      - "9001:9001"   # MinIO Console
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin         
      MINIO_ROOT_PASSWORD: minioadmin     
    command: server /data --console-address ":9001"
    restart: unless-stopped

  app:
    image: node:20
    container_name: pnpm-app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      #- /usr/src/app/node_modules
    command: sh -c "npm install -g pnpm && pnpm install && pnpm dev"
    environment:
      - OPENAI_API_KEY=xxx
      - OPENAI_BASE_URL=xxx
      - POSTGRES_URL=postgres://user:demo1234@postgres:5432/mydb
      - MINIO_ENDPOINT=localhost
      - MINIO_PORT=9000
      - MINIO_USE_SSL=false
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=aicover
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=""
      - NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
      - NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/
      - STRIPE_PUBLIC_KEY=""
      - STRIPE_PRIVATE_KEY=""
      - WEB_BASE_URI=""
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data:
  minio-data: